### ISSUE TITLE
[Frontend] Display average evaluation scores of each student in their table

### ISSUE THREAD

**Issue by gracexin2003** [CMU-313/fall22-hw3-team-otters#6]
For each student to be evaluated, pull their averaged scores for each dimension from the backend, and display them in the last row of the table.

Estimated effort/time: 3 hours for the code exploration + implementation; 2 more hours for debugging + testing

Test plan: Since this is a frontend feature, we will test by pulling the changes onto our local machines, running the code, and record the results when interacting with the feature.

Depends on #3

**Comment by lywu-andrew** [comment]
This issue was resolved by #8
